// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCClNMvIZkHk4Zv64kIWX-FnYacbrfCdS8',
    appId: '1:888885396697:web:fba23c45dd346d5763aac8',
    messagingSenderId: '888885396697',
    projectId: 'mood-tracker-abraham',
    authDomain: 'mood-tracker-abraham.firebaseapp.com',
    storageBucket: 'mood-tracker-abraham.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr9FhZn0dTBJDwvJySiB6ycS4IUNbv0OE',
    appId: '1:888885396697:android:4c9ec52b8f32553f63aac8',
    messagingSenderId: '888885396697',
    projectId: 'mood-tracker-abraham',
    storageBucket: 'mood-tracker-abraham.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTYfd1cM7IfnSbn8T-f58uyb4xocsRvxo',
    appId: '1:888885396697:ios:feca334823f4e2bb63aac8',
    messagingSenderId: '888885396697',
    projectId: 'mood-tracker-abraham',
    storageBucket: 'mood-tracker-abraham.appspot.com',
    iosBundleId: 'com.example.moodTracker',
  );
}
